server.port=${PORT:8081}
logging.level.org.atmosphere = warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false

vaadin.devmode.sessionSerialization.enabled=true
vaadin.serialization.transients.include-packages=com.example.application
vaadin.kubernetes.redis.service-name=redis-service
vaadin.kubernetes.sticky-session-cookie-name=vaadin-session

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/orman
spring.datasource.username=${DB_USERNAME:orman}
spring.datasource.password=${DB_PASSWORD:orman}