apiVersion: v1
kind: Service
metadata:
  name: kits-demo-stable
  namespace: default
spec:
  selector:
    app: kits-demo
  ports:
    - name: http
      port: 80
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kits-demo-canary
  namespace: default
spec:
  selector:
    app: kits-demo
  ports:
    - name: http
      port: 80
      targetPort: 8081
